version: "3"

tasks:
  format:
    desc: Format the codebase.
    cmds:
      - gofumpt.exe -l -w .
      - golines.exe -l -w .

  build:
    desc: Builds the application binary.
    cmds:
      - go build

  lint:
    desc: Runs linters on the codebase.
    cmds:
      - golangci-lint run ./...

  test:
    desc: Run all unit tests.
    cmds:
      - go test -race ./...
