name: Build

on: [push, pull_request]

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.55.2

    - name: Setup Just
      uses: extractions/setup-just@v1

    - name: Lint
      run: just lint

    - name: Test
      run: just test

    - name: Build
      run: just build

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.out
        fail_ci_if_error: true
